
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/baijia/specs.git'

#use_frameworks!

target 'BJPlayerManagerUI_Example' do
  pod 'BJPlayerManagerUI'
  pod 'MBProgressHUD'

  target 'BJPlayerManagerUI_Tests' do
    inherit! :search_paths

    
  end
end
